[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "pnpm dev"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://your-site.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

